hidden_dim: 128                   # (int) hidden dimension for interior recurrent layers
num_layers: 1                     # (int) the number of recurrent layers
last_step: false                  # (bool) use last sequence step as output